/* tslint:disable */
/* eslint-disable */
/**
 * CDL.Game | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface GameMapDto
 */
export interface GameMapDto {
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof GameMapDto
     */
    'nodesByLevel'?: Array<Array<string>>;
}
/**
 * 
 * @export
 * @interface GameNodeDto
 */
export interface GameNodeDto {
    /**
     * 
     * @type {string}
     * @memberof GameNodeDto
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface GameServiceDto
 */
export interface GameServiceDto {
    /**
     * 
     * @type {number}
     * @memberof GameServiceDto
     */
    'playerState'?: number;
    /**
     * 
     * @type {GameMapDto}
     * @memberof GameServiceDto
     */
    'map'?: GameMapDto;
    /**
     * 
     * @type {GameNodeDto}
     * @memberof GameServiceDto
     */
    'currentNode'?: GameNodeDto | null;
}
/**
 * 
 * @export
 * @interface IGameDto
 */
export interface IGameDto {
    /**
     * 
     * @type {string}
     * @memberof IGameDto
     */
    'playerState'?: string;
}
/**
 * 
 * @export
 * @interface MoveResponse
 */
export interface MoveResponse {
    /**
     * 
     * @type {number}
     * @memberof MoveResponse
     */
    'index'?: number;
}

/**
 * CDLGameApi - axios parameter creator
 * @export
 */
export const CDLGameApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CDLGameApi - functional programming interface
 * @export
 */
export const CDLGameApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CDLGameApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rootGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rootGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CDLGameApi.rootGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CDLGameApi - factory interface
 * @export
 */
export const CDLGameApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CDLGameApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.rootGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CDLGameApi - interface
 * @export
 * @interface CDLGameApi
 */
export interface CDLGameApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CDLGameApiInterface
     */
    rootGet(options?: RawAxiosRequestConfig): AxiosPromise<string>;

}

/**
 * CDLGameApi - object-oriented interface
 * @export
 * @class CDLGameApi
 * @extends {BaseAPI}
 */
export class CDLGameApi extends BaseAPI implements CDLGameApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CDLGameApi
     */
    public rootGet(options?: RawAxiosRequestConfig) {
        return CDLGameApiFp(this.configuration).rootGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GameApi - axios parameter creator
 * @export
 */
export const GameApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameTestGameStateGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Game/Test/GameState`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameTestGetStateGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Game/Test/GetState`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {MoveResponse} moveResponse 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameTestMoveToNodePost: async (moveResponse: MoveResponse, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'moveResponse' is not null or undefined
            assertParamExists('gameTestMoveToNodePost', 'moveResponse', moveResponse)
            const localVarPath = `/Game/Test/MoveToNode`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(moveResponse, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GameApi - functional programming interface
 * @export
 */
export const GameApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GameApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gameTestGameStateGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GameServiceDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gameTestGameStateGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GameApi.gameTestGameStateGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gameTestGetStateGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IGameDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gameTestGetStateGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GameApi.gameTestGetStateGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {MoveResponse} moveResponse 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gameTestMoveToNodePost(moveResponse: MoveResponse, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gameTestMoveToNodePost(moveResponse, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GameApi.gameTestMoveToNodePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GameApi - factory interface
 * @export
 */
export const GameApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GameApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameTestGameStateGet(options?: RawAxiosRequestConfig): AxiosPromise<GameServiceDto> {
            return localVarFp.gameTestGameStateGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameTestGetStateGet(options?: RawAxiosRequestConfig): AxiosPromise<IGameDto> {
            return localVarFp.gameTestGetStateGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {MoveResponse} moveResponse 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameTestMoveToNodePost(moveResponse: MoveResponse, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.gameTestMoveToNodePost(moveResponse, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GameApi - interface
 * @export
 * @interface GameApi
 */
export interface GameApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApiInterface
     */
    gameTestGameStateGet(options?: RawAxiosRequestConfig): AxiosPromise<GameServiceDto>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApiInterface
     */
    gameTestGetStateGet(options?: RawAxiosRequestConfig): AxiosPromise<IGameDto>;

    /**
     * 
     * @param {MoveResponse} moveResponse 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApiInterface
     */
    gameTestMoveToNodePost(moveResponse: MoveResponse, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * GameApi - object-oriented interface
 * @export
 * @class GameApi
 * @extends {BaseAPI}
 */
export class GameApi extends BaseAPI implements GameApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public gameTestGameStateGet(options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration).gameTestGameStateGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public gameTestGetStateGet(options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration).gameTestGetStateGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {MoveResponse} moveResponse 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public gameTestMoveToNodePost(moveResponse: MoveResponse, options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration).gameTestMoveToNodePost(moveResponse, options).then((request) => request(this.axios, this.basePath));
    }
}



